#include "usecase/maze_pipeline.h"

#include <chrono>
#include <iomanip>
#include <string>

#include "application/services/maze_generation.h"
#include "application/services/maze_runtime_context.h"
#include "application/services/maze_solver.h"
namespace {

using Clock = std::chrono::high_resolution_clock;

const std::string kResetColor = "\033[0m";
const std::string kGreenColor = "\033[32m";

auto IsStartNodeValid(const Config::MazeConfig& maze) -> bool {
  return maze.start_node.first >= 0 &&
         maze.start_node.first < maze.height &&
         maze.start_node.second >= 0 &&
         maze.start_node.second < maze.width;
}

auto ResolveStartNode(const Config::MazeConfig& maze) -> std::pair<int, int> {
  if (IsStartNodeValid(maze)) {
    return maze.start_node;
  }
  return {0, 0};
}

void MaybeLogAdjustedStart(const Config::MazeConfig& maze,
                           const Config::AlgorithmInfo& algo_info,
                           int start_row, int start_col, std::ostream& out) {
  if (IsStartNodeValid(maze)) {
    return;
  }

  if (algo_info.type == MazeGeneration::MazeAlgorithmType::DFS ||
      algo_info.type == MazeGeneration::MazeAlgorithmType::PRIMS ||
      algo_info.type == MazeGeneration::MazeAlgorithmType::GROWING_TREE) {
    out << "Adjusted maze generation start point to (" << start_row << ","
        << start_col
        << ") due to out-of-bounds config START_NODE for DFS/Prims/Growing "
           "Tree."
        << std::endl;
  }
}

auto PrepareMazeGrid(const Config::MazeConfig& maze) -> MazeDomain::MazeGrid {
  if (maze.height <= 0 || maze.width <= 0) {
    return {};
  }
  const auto kGridHeight = static_cast<size_t>(maze.height);
  const auto kGridWidth = static_cast<size_t>(maze.width);
  return {kGridHeight, MazeDomain::MazeGrid::value_type(kGridWidth)};
}

auto BuildTopology2D(const Config::MazeConfig& maze) -> MazeDomain::GridTopology2D {
  return MazeDomain::GridTopology2D(
      MazeDomain::GridSize2D{.height = maze.height, .width = maze.width});
}

void RunSolver(MazeDomain::MazeGrid& maze_grid,
               const MazeDomain::GridTopology2D& topology,
               const Config::AlgorithmInfo& algo_info,
               const Config::AppConfig& config,
               MazeSolver::SolverAlgorithmType solver_type,
               const char* solver_label, std::ostream& out,
               std::ostream& err) {
  out << "--- " << solver_label << " Solving (" << algo_info.name << ") ---"
      << std::endl;
  const auto kStartTime = Clock::now();
  const auto runtime_context = MazeApplication::BuildRuntimeContext2D(
      maze_grid, topology, algo_info.type, solver_type, config);
  const auto kResult = MazeSolver::Solve(runtime_context);
  const std::string kSolverName = MazeSolver::AlgorithmName(solver_type);
  const std::string kDisplayName =
      kSolverName.empty() ? "Solver" : kSolverName;
  if (kResult.cancelled_) {
    err << kDisplayName << ": cancelled." << std::endl;
  } else if (!kResult.found_) {
    err << kDisplayName << ": no path found." << std::endl;
  } else {
    out << kDisplayName << ": path length=" << kResult.path_.size()
        << " (maze generated by " << algo_info.name << ")" << std::endl;
  }
  const auto kEndTime = Clock::now();
  const auto kTimeTaken = std::chrono::duration<double>(kEndTime - kStartTime);
  out << kGreenColor << std::fixed << std::setprecision(3) << "Time for "
      << solver_label << " solving: " << kTimeTaken.count() << " s"
      << kResetColor << std::endl;
}

void RunGenerationForAlgorithm(const Config::AppConfig& config,
                               const Config::AlgorithmInfo& algo_info,
                               std::ostream& out, std::ostream& err) {
  out << "\n--- Processing for Maze Generation Algorithm: " << algo_info.name
      << " ---" << std::endl;

  const MazeDomain::GridTopology2D topology = BuildTopology2D(config.maze);
  auto maze_grid = PrepareMazeGrid(config.maze);

  out << "--- Maze Generation (" << algo_info.name << ") ---" << std::endl;
  const auto kStartNode = ResolveStartNode(config.maze);
  const int kGenStartRow = kStartNode.first;
  const int kGenStartCol = kStartNode.second;
  MaybeLogAdjustedStart(config.maze, algo_info, kGenStartRow, kGenStartCol,
                        out);

  const auto kStartTime = Clock::now();
  auto runtime_context = MazeApplication::BuildRuntimeContext2D(
      maze_grid, topology, algo_info.type,
      MazeSolver::SolverAlgorithmType::BFS, config);
  runtime_context.start_node_ = {kGenStartRow, kGenStartCol};
  MazeGeneration::generate_maze_structure(runtime_context);
  const auto kEndTime = Clock::now();
  const auto kTimeTaken = std::chrono::duration<double>(kEndTime - kStartTime);
  out << kGreenColor << std::fixed << std::setprecision(3)
      << "Time for maze generation: " << kTimeTaken.count() << " s"
      << kResetColor << std::endl;

  out << "Maze generated." << std::endl;

  for (const auto& solver_info : config.maze.search_algorithms) {
    RunSolver(maze_grid, topology, algo_info, config, solver_info.type,
              solver_info.name.c_str(), out, err);
  }
}

}  // namespace

namespace MazeUsecase {

auto RunGenerationPipeline(const Config::AppConfig& config, std::ostream& out,
                           std::ostream& err) -> PipelineStatus {
  if (config.maze.dimension == Config::MazeRuntimeDimension::D3) {
    err << "Dimension=3 is parsed and validated, but 3D pipeline is not "
           "implemented yet."
        << std::endl;
    return PipelineStatus::kUnsupportedDimension;
  }

  for (const auto& algo_info : config.maze.generation_algorithms) {
    RunGenerationForAlgorithm(config, algo_info, out, err);
  }
  return PipelineStatus::kOk;
}

}  // namespace MazeUsecase
